const  HTTP_STATUS_CODE_OK = 200
const  HTTP_STATUS_CODE_ACCEPTED = 202
const  HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR = 500

const  BASIC_DB_OPERATION_PERIOD = 1000


module.exports = { 	HTTP_STATUS_CODE_ACCEPTED,
					HTTP_STATUS_CODE_OK,
					HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR,
					BASIC_DB_OPERATION_PERIOD
				 }